import style from "@/app/layout.module.css";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={style.container}>
          <header>
            <Link href={"/"}>👕 Shopping Mall 👔</Link>
          </header>
          {children}
          <footer>하단</footer>
        </div>
      </body>
    </html>
  );
}
